FROM htcondor/mini
ENTRYPOINT ["sh"]
#RUN dnf update libstd++6
#RUN pip3 install jupyter pandas numpy
#RUN pip3 install 'python-lsp-server[all]'
#RUN groupadd -r mygroup && useradd -r -g mygroup myuser
#RUN /start.sh
#USER 1000:1000
#USER tea
#ENTRYPOINT ["jupyter-notebook", "--ip=0.0.0.0", "--port=8080"]
#ENTRYPOINT ["sh"]
