# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pyhypercube
else:
    import _pyhypercube

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SHARED_PTR_DISOWN = _pyhypercube.SHARED_PTR_DISOWN
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyhypercube.delete_SwigPyIterator

    def value(self):
        return _pyhypercube.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyhypercube.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyhypercube.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyhypercube.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyhypercube.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyhypercube.SwigPyIterator_copy(self)

    def next(self):
        return _pyhypercube.SwigPyIterator_next(self)

    def __next__(self):
        return _pyhypercube.SwigPyIterator___next__(self)

    def previous(self):
        return _pyhypercube.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyhypercube.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyhypercube.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyhypercube.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyhypercube.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyhypercube.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyhypercube.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyhypercube.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _pyhypercube:
_pyhypercube.SwigPyIterator_swigregister(SwigPyIterator)
class DVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyhypercube.DVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyhypercube.DVector___nonzero__(self)

    def __bool__(self):
        return _pyhypercube.DVector___bool__(self)

    def __len__(self):
        return _pyhypercube.DVector___len__(self)

    def __getslice__(self, i, j):
        return _pyhypercube.DVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyhypercube.DVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyhypercube.DVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyhypercube.DVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyhypercube.DVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyhypercube.DVector___setitem__(self, *args)

    def pop(self):
        return _pyhypercube.DVector_pop(self)

    def append(self, x):
        return _pyhypercube.DVector_append(self, x)

    def empty(self):
        return _pyhypercube.DVector_empty(self)

    def size(self):
        return _pyhypercube.DVector_size(self)

    def swap(self, v):
        return _pyhypercube.DVector_swap(self, v)

    def begin(self):
        return _pyhypercube.DVector_begin(self)

    def end(self):
        return _pyhypercube.DVector_end(self)

    def rbegin(self):
        return _pyhypercube.DVector_rbegin(self)

    def rend(self):
        return _pyhypercube.DVector_rend(self)

    def clear(self):
        return _pyhypercube.DVector_clear(self)

    def get_allocator(self):
        return _pyhypercube.DVector_get_allocator(self)

    def pop_back(self):
        return _pyhypercube.DVector_pop_back(self)

    def erase(self, *args):
        return _pyhypercube.DVector_erase(self, *args)

    def __init__(self, *args):
        _pyhypercube.DVector_swiginit(self, _pyhypercube.new_DVector(*args))

    def push_back(self, x):
        return _pyhypercube.DVector_push_back(self, x)

    def front(self):
        return _pyhypercube.DVector_front(self)

    def back(self):
        return _pyhypercube.DVector_back(self)

    def assign(self, n, x):
        return _pyhypercube.DVector_assign(self, n, x)

    def resize(self, *args):
        return _pyhypercube.DVector_resize(self, *args)

    def insert(self, *args):
        return _pyhypercube.DVector_insert(self, *args)

    def reserve(self, n):
        return _pyhypercube.DVector_reserve(self, n)

    def capacity(self):
        return _pyhypercube.DVector_capacity(self)
    __swig_destroy__ = _pyhypercube.delete_DVector

# Register DVector in _pyhypercube:
_pyhypercube.DVector_swigregister(DVector)
class FVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyhypercube.FVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyhypercube.FVector___nonzero__(self)

    def __bool__(self):
        return _pyhypercube.FVector___bool__(self)

    def __len__(self):
        return _pyhypercube.FVector___len__(self)

    def __getslice__(self, i, j):
        return _pyhypercube.FVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyhypercube.FVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyhypercube.FVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyhypercube.FVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyhypercube.FVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyhypercube.FVector___setitem__(self, *args)

    def pop(self):
        return _pyhypercube.FVector_pop(self)

    def append(self, x):
        return _pyhypercube.FVector_append(self, x)

    def empty(self):
        return _pyhypercube.FVector_empty(self)

    def size(self):
        return _pyhypercube.FVector_size(self)

    def swap(self, v):
        return _pyhypercube.FVector_swap(self, v)

    def begin(self):
        return _pyhypercube.FVector_begin(self)

    def end(self):
        return _pyhypercube.FVector_end(self)

    def rbegin(self):
        return _pyhypercube.FVector_rbegin(self)

    def rend(self):
        return _pyhypercube.FVector_rend(self)

    def clear(self):
        return _pyhypercube.FVector_clear(self)

    def get_allocator(self):
        return _pyhypercube.FVector_get_allocator(self)

    def pop_back(self):
        return _pyhypercube.FVector_pop_back(self)

    def erase(self, *args):
        return _pyhypercube.FVector_erase(self, *args)

    def __init__(self, *args):
        _pyhypercube.FVector_swiginit(self, _pyhypercube.new_FVector(*args))

    def push_back(self, x):
        return _pyhypercube.FVector_push_back(self, x)

    def front(self):
        return _pyhypercube.FVector_front(self)

    def back(self):
        return _pyhypercube.FVector_back(self)

    def assign(self, n, x):
        return _pyhypercube.FVector_assign(self, n, x)

    def resize(self, *args):
        return _pyhypercube.FVector_resize(self, *args)

    def insert(self, *args):
        return _pyhypercube.FVector_insert(self, *args)

    def reserve(self, n):
        return _pyhypercube.FVector_reserve(self, n)

    def capacity(self):
        return _pyhypercube.FVector_capacity(self)
    __swig_destroy__ = _pyhypercube.delete_FVector

# Register FVector in _pyhypercube:
_pyhypercube.FVector_swigregister(FVector)
class UInt8Vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyhypercube.UInt8Vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyhypercube.UInt8Vector___nonzero__(self)

    def __bool__(self):
        return _pyhypercube.UInt8Vector___bool__(self)

    def __len__(self):
        return _pyhypercube.UInt8Vector___len__(self)

    def __getslice__(self, i, j):
        return _pyhypercube.UInt8Vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyhypercube.UInt8Vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyhypercube.UInt8Vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyhypercube.UInt8Vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyhypercube.UInt8Vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyhypercube.UInt8Vector___setitem__(self, *args)

    def pop(self):
        return _pyhypercube.UInt8Vector_pop(self)

    def append(self, x):
        return _pyhypercube.UInt8Vector_append(self, x)

    def empty(self):
        return _pyhypercube.UInt8Vector_empty(self)

    def size(self):
        return _pyhypercube.UInt8Vector_size(self)

    def swap(self, v):
        return _pyhypercube.UInt8Vector_swap(self, v)

    def begin(self):
        return _pyhypercube.UInt8Vector_begin(self)

    def end(self):
        return _pyhypercube.UInt8Vector_end(self)

    def rbegin(self):
        return _pyhypercube.UInt8Vector_rbegin(self)

    def rend(self):
        return _pyhypercube.UInt8Vector_rend(self)

    def clear(self):
        return _pyhypercube.UInt8Vector_clear(self)

    def get_allocator(self):
        return _pyhypercube.UInt8Vector_get_allocator(self)

    def pop_back(self):
        return _pyhypercube.UInt8Vector_pop_back(self)

    def erase(self, *args):
        return _pyhypercube.UInt8Vector_erase(self, *args)

    def __init__(self, *args):
        _pyhypercube.UInt8Vector_swiginit(self, _pyhypercube.new_UInt8Vector(*args))

    def push_back(self, x):
        return _pyhypercube.UInt8Vector_push_back(self, x)

    def front(self):
        return _pyhypercube.UInt8Vector_front(self)

    def back(self):
        return _pyhypercube.UInt8Vector_back(self)

    def assign(self, n, x):
        return _pyhypercube.UInt8Vector_assign(self, n, x)

    def resize(self, *args):
        return _pyhypercube.UInt8Vector_resize(self, *args)

    def insert(self, *args):
        return _pyhypercube.UInt8Vector_insert(self, *args)

    def reserve(self, n):
        return _pyhypercube.UInt8Vector_reserve(self, n)

    def capacity(self):
        return _pyhypercube.UInt8Vector_capacity(self)
    __swig_destroy__ = _pyhypercube.delete_UInt8Vector

# Register UInt8Vector in _pyhypercube:
_pyhypercube.UInt8Vector_swigregister(UInt8Vector)
class SubtaskResultsVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyhypercube.SubtaskResultsVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyhypercube.SubtaskResultsVector___nonzero__(self)

    def __bool__(self):
        return _pyhypercube.SubtaskResultsVector___bool__(self)

    def __len__(self):
        return _pyhypercube.SubtaskResultsVector___len__(self)

    def __getslice__(self, i, j):
        return _pyhypercube.SubtaskResultsVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyhypercube.SubtaskResultsVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyhypercube.SubtaskResultsVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyhypercube.SubtaskResultsVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyhypercube.SubtaskResultsVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyhypercube.SubtaskResultsVector___setitem__(self, *args)

    def pop(self):
        return _pyhypercube.SubtaskResultsVector_pop(self)

    def append(self, x):
        return _pyhypercube.SubtaskResultsVector_append(self, x)

    def empty(self):
        return _pyhypercube.SubtaskResultsVector_empty(self)

    def size(self):
        return _pyhypercube.SubtaskResultsVector_size(self)

    def swap(self, v):
        return _pyhypercube.SubtaskResultsVector_swap(self, v)

    def begin(self):
        return _pyhypercube.SubtaskResultsVector_begin(self)

    def end(self):
        return _pyhypercube.SubtaskResultsVector_end(self)

    def rbegin(self):
        return _pyhypercube.SubtaskResultsVector_rbegin(self)

    def rend(self):
        return _pyhypercube.SubtaskResultsVector_rend(self)

    def clear(self):
        return _pyhypercube.SubtaskResultsVector_clear(self)

    def get_allocator(self):
        return _pyhypercube.SubtaskResultsVector_get_allocator(self)

    def pop_back(self):
        return _pyhypercube.SubtaskResultsVector_pop_back(self)

    def erase(self, *args):
        return _pyhypercube.SubtaskResultsVector_erase(self, *args)

    def __init__(self, *args):
        _pyhypercube.SubtaskResultsVector_swiginit(self, _pyhypercube.new_SubtaskResultsVector(*args))

    def push_back(self, x):
        return _pyhypercube.SubtaskResultsVector_push_back(self, x)

    def front(self):
        return _pyhypercube.SubtaskResultsVector_front(self)

    def back(self):
        return _pyhypercube.SubtaskResultsVector_back(self)

    def assign(self, n, x):
        return _pyhypercube.SubtaskResultsVector_assign(self, n, x)

    def resize(self, *args):
        return _pyhypercube.SubtaskResultsVector_resize(self, *args)

    def insert(self, *args):
        return _pyhypercube.SubtaskResultsVector_insert(self, *args)

    def reserve(self, n):
        return _pyhypercube.SubtaskResultsVector_reserve(self, n)

    def capacity(self):
        return _pyhypercube.SubtaskResultsVector_capacity(self)
    __swig_destroy__ = _pyhypercube.delete_SubtaskResultsVector

# Register SubtaskResultsVector in _pyhypercube:
_pyhypercube.SubtaskResultsVector_swigregister(SubtaskResultsVector)
class RandomBitGenerator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyhypercube.delete_RandomBitGenerator

    def __call__(self):
        return _pyhypercube.RandomBitGenerator___call__(self)

    def nbits(self):
        return _pyhypercube.RandomBitGenerator_nbits(self)

    def copy(self):
        return _pyhypercube.RandomBitGenerator_copy(self)

    def max(self):
        return _pyhypercube.RandomBitGenerator_max(self)

    def discard(self):
        return _pyhypercube.RandomBitGenerator_discard(self)

    def discardN(self, n):
        return _pyhypercube.RandomBitGenerator_discardN(self, n)

    def jumpTo(self, pos):
        return _pyhypercube.RandomBitGenerator_jumpTo(self, pos)
    counter = property(_pyhypercube.RandomBitGenerator_counter_get, _pyhypercube.RandomBitGenerator_counter_set)

# Register RandomBitGenerator in _pyhypercube:
_pyhypercube.RandomBitGenerator_swigregister(RandomBitGenerator)
class RandomNumberGeneratorDescription(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    rng_id = property(_pyhypercube.RandomNumberGeneratorDescription_rng_id_get, _pyhypercube.RandomNumberGeneratorDescription_rng_id_set)
    seed = property(_pyhypercube.RandomNumberGeneratorDescription_seed_get, _pyhypercube.RandomNumberGeneratorDescription_seed_set)
    offset = property(_pyhypercube.RandomNumberGeneratorDescription_offset_get, _pyhypercube.RandomNumberGeneratorDescription_offset_set)

    def __eq__(self, other):
        return _pyhypercube.RandomNumberGeneratorDescription___eq__(self, other)

    def __init__(self):
        _pyhypercube.RandomNumberGeneratorDescription_swiginit(self, _pyhypercube.new_RandomNumberGeneratorDescription())
    __swig_destroy__ = _pyhypercube.delete_RandomNumberGeneratorDescription

# Register RandomNumberGeneratorDescription in _pyhypercube:
_pyhypercube.RandomNumberGeneratorDescription_swigregister(RandomNumberGeneratorDescription)
class BitsRepackDescription(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    src_little_endian = property(_pyhypercube.BitsRepackDescription_src_little_endian_get, _pyhypercube.BitsRepackDescription_src_little_endian_set)
    dst_little_endian = property(_pyhypercube.BitsRepackDescription_dst_little_endian_get, _pyhypercube.BitsRepackDescription_dst_little_endian_set)
    bits_per_sample = property(_pyhypercube.BitsRepackDescription_bits_per_sample_get, _pyhypercube.BitsRepackDescription_bits_per_sample_set)

    def __eq__(self, other):
        return _pyhypercube.BitsRepackDescription___eq__(self, other)

    def __init__(self):
        _pyhypercube.BitsRepackDescription_swiginit(self, _pyhypercube.new_BitsRepackDescription())
    __swig_destroy__ = _pyhypercube.delete_BitsRepackDescription

# Register BitsRepackDescription in _pyhypercube:
_pyhypercube.BitsRepackDescription_swigregister(BitsRepackDescription)

def createGenerator(*args):
    return _pyhypercube.createGenerator(*args)
class Chi2BasedProblem(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    N = property(_pyhypercube.Chi2BasedProblem_N_get, _pyhypercube.Chi2BasedProblem_N_set)
    n_cells_total = property(_pyhypercube.Chi2BasedProblem_n_cells_total_get, _pyhypercube.Chi2BasedProblem_n_cells_total_set)

    def __eq__(self, other):
        return _pyhypercube.Chi2BasedProblem___eq__(self, other)

    def __init__(self):
        _pyhypercube.Chi2BasedProblem_swiginit(self, _pyhypercube.new_Chi2BasedProblem())
    __swig_destroy__ = _pyhypercube.delete_Chi2BasedProblem

# Register Chi2BasedProblem in _pyhypercube:
_pyhypercube.Chi2BasedProblem_swigregister(Chi2BasedProblem)
class StatiscticalTestResults(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    dof = property(_pyhypercube.StatiscticalTestResults_dof_get, _pyhypercube.StatiscticalTestResults_dof_set)
    chi2 = property(_pyhypercube.StatiscticalTestResults_chi2_get, _pyhypercube.StatiscticalTestResults_chi2_set)
    chi2cdf = property(_pyhypercube.StatiscticalTestResults_chi2cdf_get, _pyhypercube.StatiscticalTestResults_chi2cdf_set)
    mean = property(_pyhypercube.StatiscticalTestResults_mean_get, _pyhypercube.StatiscticalTestResults_mean_set)
    sum = property(_pyhypercube.StatiscticalTestResults_sum_get, _pyhypercube.StatiscticalTestResults_sum_set)
    sum2 = property(_pyhypercube.StatiscticalTestResults_sum2_get, _pyhypercube.StatiscticalTestResults_sum2_set)
    N = property(_pyhypercube.StatiscticalTestResults_N_get, _pyhypercube.StatiscticalTestResults_N_set)

    def __eq__(self, other):
        return _pyhypercube.StatiscticalTestResults___eq__(self, other)

    def __init__(self):
        _pyhypercube.StatiscticalTestResults_swiginit(self, _pyhypercube.new_StatiscticalTestResults())
    __swig_destroy__ = _pyhypercube.delete_StatiscticalTestResults

# Register StatiscticalTestResults in _pyhypercube:
_pyhypercube.StatiscticalTestResults_swigregister(StatiscticalTestResults)
class SubtaskParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Ntasks = property(_pyhypercube.SubtaskParameters_Ntasks_get, _pyhypercube.SubtaskParameters_Ntasks_set)
    cur_task = property(_pyhypercube.SubtaskParameters_cur_task_get, _pyhypercube.SubtaskParameters_cur_task_set)

    def __eq__(self, other):
        return _pyhypercube.SubtaskParameters___eq__(self, other)

    def __init__(self):
        _pyhypercube.SubtaskParameters_swiginit(self, _pyhypercube.new_SubtaskParameters())
    __swig_destroy__ = _pyhypercube.delete_SubtaskParameters

# Register SubtaskParameters in _pyhypercube:
_pyhypercube.SubtaskParameters_swigregister(SubtaskParameters)
class SubtaskResults(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    sum = property(_pyhypercube.SubtaskResults_sum_get, _pyhypercube.SubtaskResults_sum_set)
    sum2 = property(_pyhypercube.SubtaskResults_sum2_get, _pyhypercube.SubtaskResults_sum2_set)

    def __eq__(self, other):
        return _pyhypercube.SubtaskResults___eq__(self, other)

    def __init__(self):
        _pyhypercube.SubtaskResults_swiginit(self, _pyhypercube.new_SubtaskResults())
    __swig_destroy__ = _pyhypercube.delete_SubtaskResults

# Register SubtaskResults in _pyhypercube:
_pyhypercube.SubtaskResults_swigregister(SubtaskResults)
class DistributionSampler(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyhypercube.delete_DistributionSampler

    def copy(self):
        return _pyhypercube.DistributionSampler_copy(self)

    def __call__(self, rng):
        return _pyhypercube.DistributionSampler___call__(self, rng)

    def max(self):
        return _pyhypercube.DistributionSampler_max(self)

    def discardN(self, N, rng):
        return _pyhypercube.DistributionSampler_discardN(self, N, rng)

# Register DistributionSampler in _pyhypercube:
_pyhypercube.DistributionSampler_swigregister(DistributionSampler)
class HypercubeProblem(Chi2BasedProblem):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyhypercube.HypercubeProblem_swiginit(self, _pyhypercube.new_HypercubeProblem(*args))

    def __eq__(self, other):
        return _pyhypercube.HypercubeProblem___eq__(self, other)
    dim = property(_pyhypercube.HypercubeProblem_dim_get, _pyhypercube.HypercubeProblem_dim_set)
    m_intervals_per_dim = property(_pyhypercube.HypercubeProblem_m_intervals_per_dim_get, _pyhypercube.HypercubeProblem_m_intervals_per_dim_set)
    stride = property(_pyhypercube.HypercubeProblem_stride_get, _pyhypercube.HypercubeProblem_stride_set)
    __swig_destroy__ = _pyhypercube.delete_HypercubeProblem

# Register HypercubeProblem in _pyhypercube:
_pyhypercube.HypercubeProblem_swigregister(HypercubeProblem)
class HypercubeSampler(DistributionSampler):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pyhypercube.HypercubeSampler_swiginit(self, _pyhypercube.new_HypercubeSampler(*args))

    def copy(self):
        return _pyhypercube.HypercubeSampler_copy(self)

    def __call__(self, rng):
        return _pyhypercube.HypercubeSampler___call__(self, rng)

    def discardN(self, N, rng):
        return _pyhypercube.HypercubeSampler_discardN(self, N, rng)

    def max(self):
        return _pyhypercube.HypercubeSampler_max(self)
    __swig_destroy__ = _pyhypercube.delete_HypercubeSampler

# Register HypercubeSampler in _pyhypercube:
_pyhypercube.HypercubeSampler_swigregister(HypercubeSampler)
class Chi2BasedTest1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _pyhypercube.Chi2BasedTest1_swiginit(self, _pyhypercube.new_Chi2BasedTest1())
    __swig_destroy__ = _pyhypercube.delete_Chi2BasedTest1

    def run(self, problem, subtask, sampler, rng, n_threads=1):
        return _pyhypercube.Chi2BasedTest1_run(self, problem, subtask, sampler, rng, n_threads)

    def collect(self, problem, n_subtasks, subtask_results):
        return _pyhypercube.Chi2BasedTest1_collect(self, problem, n_subtasks, subtask_results)

# Register Chi2BasedTest1 in _pyhypercube:
_pyhypercube.Chi2BasedTest1_swigregister(Chi2BasedTest1)

def run(problem, subtask, sampler):
    return _pyhypercube.run(problem, subtask, sampler)

